from typing import List, Dict, Any

def generate_scrapling_code(
    history: List[Dict[str, Any]],
    solve_cloudflare: bool = True,
    block_ads: bool = True,
    disable_resources: bool = False
) -> str:
    lines = []
    lines.append("# Generated by Scrapling Visual Builder")
    lines.append("from scrapling.fetchers import StealthyFetcher")
    lines.append("")
    
    start_url = "https://example.com"
    for step in history:
        if step["action"] == "navigate":
            start_url = step["url"]
            break

    interactions = [step for step in history if step["action"] in ["click", "fill", "scroll", "back", "forward", "reload"]]
    extractions = [step for step in history if step["action"] == "extract"]
    
    # Build dynamic fetch arguments
    fetch_args = f"'{start_url}', headless=True"
    if not solve_cloudflare:
        fetch_args += ", solve_cloudflare=False"
    if not block_ads:
        fetch_args += ", block_ads=False"
    if disable_resources:
        fetch_args += ", disable_resources=True"
        
    if interactions:
        lines.append("def perform_actions(page):")
        for step in interactions:
            action = step["action"]
            selector = step.get("selector", "").replace('\\', '\\\\')
            
            if action == "click":
                lines.append(f"    # Click element")
                lines.append(f"    page.click('{selector}')")
                lines.append("    page.wait_for_load_state('load')")
                lines.append("")
            elif action == "fill":
                lines.append(f"    # Fill input field")
                lines.append(f"    page.fill('{selector}', '{step['value']}')")
                lines.append("")
            elif action == "scroll":
                lines.append(f"    # Scroll page")
                lines.append(f"    page.evaluate('window.scrollBy(0, {step['y']})')")
                lines.append("    page.wait_for_timeout(1000)")
                lines.append("")
            elif action == "back":
                lines.append("    # Go back in history")
                lines.append("    page.go_back()")
                lines.append("    page.wait_for_load_state('load')")
                lines.append("")
            elif action == "forward":
                lines.append("    # Go forward in history")
                lines.append("    page.go_forward()")
                lines.append("    page.wait_for_load_state('load')")
                lines.append("")
            elif action == "reload":
                lines.append("    # Reload page")
                lines.append("    page.reload()")
                lines.append("    page.wait_for_load_state('load')")
                lines.append("")
        
        lines.append("def run_scraper():")
        lines.append(f"    # Fetch the page stealthily and run automation actions")
        lines.append(f"    response = StealthyFetcher.fetch({fetch_args}, page_action=perform_actions)")
        lines.append("")
    else:
        lines.append("def run_scraper():")
        lines.append(f"    # Fetch page stealthily")
        lines.append(f"    response = StealthyFetcher.fetch({fetch_args})")
        lines.append("")

    list_extractions = [step for step in history if step["action"] == "extract_list"]

    if extractions:
        lines.append("    # Extract data")
        for step in extractions:
            var_name = step.get("name", "data").lower().replace(" ", "_")
            selector = step["selector"].replace('\\', '\\\\')
            attr = step["attribute"]
            
            if attr == "text":
                lines.append(f"    # Get text from '{selector}'")
                lines.append(f"    {var_name} = response.css('{selector}::text').get_all()")
            elif attr == "html":
                lines.append(f"    # Get HTML content")
                lines.append(f"    {var_name} = response.css('{selector}').get_all()")
            else:
                lines.append(f"    # Get '{attr}' attribute")
                lines.append(f"    {var_name} = response.css('{selector}::attr({attr})').get_all()")
                
            lines.append(f"    print('{step['name']}:', {var_name})")
            lines.append("")

    if list_extractions:
        lines.append("    # Extract List Data")
        for step in list_extractions:
            var_name = step.get("name", "data").lower().replace(" ", "_")
            selector = step["selector"].replace('\\', '\\\\')
            attr = step["attribute"]
            
            if attr == "text":
                lines.append(f"    {var_name}_list = response.css('{selector}::text').get_all()")
            elif attr == "html":
                lines.append(f"    {var_name}_list = response.css('{selector}').get_all()")
            else:
                lines.append(f"    {var_name}_list = response.css('{selector}::attr({attr})').get_all()")
        
        lines.append("")
        lines.append("    # Print structured table rows")
        vars_zip = ", ".join([f"{step['name'].lower().replace(' ', '_')}" for step in list_extractions])
        vars_list = ", ".join([f"{step['name'].lower().replace(' ', '_')}_list" for step in list_extractions])
        lines.append(f"    for {vars_zip} in zip({vars_list}):")
        
        dict_items = ", ".join([f"'{step['name']}': {step['name'].lower().replace(' ', '_')}" for step in list_extractions])
        lines.append(f"        print({{{dict_items}}})")
        lines.append("")
            
    lines.append("if __name__ == '__main__':")
    lines.append("    run_scraper()")
    
    return "\n".join(lines)
