import React, { useState, useEffect, useRef } from 'react';
import { Play, Copy, Check, Terminal, Loader } from 'lucide-react';

interface CodeRunnerProps {
  code: string;
  sessionId: string | null;
  onStateUpdate: (state: any) => void;
  scrapedData?: any[];
  history?: any[];
  apiKey?: string;
}

const compileToFramework = (
  steps: any[], 
  framework: 'scrapling_sync' | 'scrapling_async' | 'playwright_python' | 'scrapy_spider',
  solveCF = true,
  blockAds = true,
  disableRes = false
): string => {
  if (steps.length === 0) {
    return "# No steps recorded yet.";
  }
  
  let startUrl = "https://example.com";
  for (const step of steps) {
    if (step.action === 'navigate') {
      startUrl = step.url || startUrl;
      break;
    }
  }
  
  const interactions = steps.filter(s => ['click', 'fill', 'scroll', 'back', 'forward', 'reload'].includes(s.action));
  const extractions = steps.filter(s => s.action === 'extract');
  const listExtractions = steps.filter(s => s.action === 'extract_list');
  const paginationStep = steps.find(s => s.action === 'pagination');
  
  const solveCFStr = solveCF ? "" : ", solve_cloudflare=False";
  const blockAdsStr = blockAds ? "" : ", block_ads=False";
  const disableResStr = disableRes ? ", disable_resources=True" : "";
  const fetchFlags = `headless=True${solveCFStr}${blockAdsStr}${disableResStr}`;

  if (framework === 'scrapling_sync') {
    const lines: string[] = [
      "# Generated by Scrapling Visual Builder",
      "from scrapling.fetchers import StealthyFetcher"
    ];
    if (paginationStep) {
      lines.push("from scrapling import Adaptor");
    }
    lines.push("");

    if (paginationStep) {
      const setupSteps = [];
      for (const step of steps) {
        if (step.action === 'pagination') break;
        if (['click', 'fill', 'scroll', 'back', 'forward', 'reload'].includes(step.action)) {
          setupSteps.push(step);
        }
      }
      lines.push("def perform_actions(page):");
      if (setupSteps.length > 0) {
        for (const step of setupSteps) {
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          if (step.action === 'click') {
            lines.push("    # Click element");
            lines.push(`    page.click('${sel}')`);
            lines.push("    page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'fill') {
            lines.push("    # Fill input field");
            lines.push(`    page.fill('${sel}', '${step.value}')`);
            lines.push("");
          } else if (step.action === 'scroll') {
            lines.push("    # Scroll page");
            lines.push(`    page.evaluate('window.scrollBy(0, ${step.y})')`);
            lines.push("    page.wait_for_timeout(1000)");
            lines.push("");
          } else if (step.action === 'back') {
            lines.push("    # Go back in history");
            lines.push("    page.go_back()");
            lines.push("    page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'forward') {
            lines.push("    # Go forward in history");
            lines.push("    page.go_forward()");
            lines.push("    page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'reload') {
            lines.push("    # Reload page");
            lines.push("    page.reload()");
            lines.push("    page.wait_for_load_state('load')");
            lines.push("");
          }
        }
      } else {
        lines.push("    pass");
        lines.push("");
      }

      const pagSel = paginationStep.selector?.replace(/\\/g, '\\\\') || '';
      const maxPages = paginationStep.max_pages || 5;

      lines.push("    # Pagination loop: extract page-by-page");
      lines.push(`    max_pages = ${maxPages}`);
      lines.push("    for page_num in range(1, max_pages + 1):");
      lines.push("        print(f'=== Scraping Page {page_num} ===')");
      lines.push("        response = Adaptor(page.content())");
      lines.push("");

      if (extractions.length > 0) {
        for (const step of extractions) {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          const attr = step.attribute;
          if (attr === 'text') {
            lines.push(`        # Get text from '${sel}'`);
            lines.push(`        ${var_name} = response.css('${sel}::text').get_all()`);
          } else if (attr === 'html') {
            lines.push(`        # Get HTML content`);
            lines.push(`        ${var_name} = response.css('${sel}').get_all()`);
          } else {
            lines.push(`        # Get '${attr}' attribute`);
            lines.push(`        ${var_name} = response.css('${sel}::attr(${attr})').get_all()`);
          }
          lines.push(`        print('${step.name}:', ${var_name})`);
          lines.push("");
        }
      }

      if (listExtractions.length > 0) {
        for (const step of listExtractions) {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          const attr = step.attribute;
          if (attr === 'text') {
            lines.push(`        ${var_name}_list = response.css('${sel}::text').get_all()`);
          } else if (attr === 'html') {
            lines.push(`        ${var_name}_list = response.css('${sel}').get_all()`);
          } else {
            lines.push(`        ${var_name}_list = response.css('${sel}::attr(${attr})').get_all()`);
          }
        }
        lines.push("");
        const vars_zip = listExtractions.map(s => s.name?.toLowerCase().replace(/\s+/g, '_') || 'data').join(', ');
        const vars_list = listExtractions.map(s => (s.name?.toLowerCase().replace(/\s+/g, '_') || 'data') + '_list').join(', ');
        lines.push(`        for ${vars_zip} in zip(${vars_list}):`);
        const dict_items = listExtractions.map(s => `'${s.name}': ${s.name?.toLowerCase().replace(/\s+/g, '_') || 'data'}`).join(', ');
        lines.push(`            print({${dict_items}})`);
        lines.push("");
      }

      lines.push("        if page_num < max_pages:");
      lines.push("            try:");
      lines.push("                # Click next button");
      lines.push(`                page.click('${pagSel}')`);
      lines.push("                page.wait_for_load_state('load')");
      lines.push("                page.wait_for_timeout(2000)");
      lines.push("            except Exception as e:");
      lines.push("                print('No more pages:', e)");
      lines.push("                break");
      lines.push("");

      lines.push("def run_scraper():");
      lines.push("    # Fetch page stealthily and run automation actions");
      lines.push(`    response = StealthyFetcher.fetch('${startUrl}', ${fetchFlags}, page_action=perform_actions)`);
    } else {
      if (interactions.length > 0) {
        lines.push("def perform_actions(page):");
        for (const step of steps) {
          if (!['click', 'fill', 'scroll', 'back', 'forward', 'reload'].includes(step.action)) continue;
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          if (step.action === 'click') {
            lines.push("    # Click element");
            lines.push(`    page.click('${sel}')`);
            lines.push("    page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'fill') {
            lines.push("    # Fill input field");
            lines.push(`    page.fill('${sel}', '${step.value}')`);
            lines.push("");
          } else if (step.action === 'scroll') {
            lines.push("    # Scroll page");
            lines.push(`    page.evaluate('window.scrollBy(0, ${step.y})')`);
            lines.push("    page.wait_for_timeout(1000)");
            lines.push("");
          } else if (step.action === 'back') {
            lines.push("    # Go back in history");
            lines.push("    page.go_back()");
            lines.push("    page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'forward') {
            lines.push("    # Go forward in history");
            lines.push("    page.go_forward()");
            lines.push("    page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'reload') {
            lines.push("    # Reload page");
            lines.push("    page.reload()");
            lines.push("    page.wait_for_load_state('load')");
            lines.push("");
          }
        }
        lines.push("def run_scraper():");
        lines.push("    # Fetch page stealthily and run automation actions");
        lines.push(`    response = StealthyFetcher.fetch('${startUrl}', ${fetchFlags}, page_action=perform_actions)`);
      } else {
        lines.push("def run_scraper():");
        lines.push("    # Fetch page stealthily");
        lines.push(`    response = StealthyFetcher.fetch('${startUrl}', ${fetchFlags})`);
      }
      lines.push("");
      
      if (extractions.length > 0) {
        lines.push("    # Extract data");
        for (const step of extractions) {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          const attr = step.attribute;
          if (attr === 'text') {
            lines.push(`    ${var_name} = response.css('${sel}::text').get_all()`);
          } else if (attr === 'html') {
            lines.push(`    ${var_name} = response.css('${sel}').get_all()`);
          } else {
            lines.push(`    ${var_name} = response.css('${sel}::attr(${attr})').get_all()`);
          }
          lines.push(`    print('${step.name}:', ${var_name})`);
          lines.push("");
        }
      }
      if (listExtractions.length > 0) {
        lines.push("    # Extract List Data");
        for (const step of listExtractions) {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          const attr = step.attribute;
          if (attr === 'text') {
            lines.push(`    ${var_name}_list = response.css('${sel}::text').get_all()`);
          } else if (attr === 'html') {
            lines.push(`    ${var_name}_list = response.css('${sel}').get_all()`);
          } else {
            lines.push(`    ${var_name}_list = response.css('${sel}::attr(${attr})').get_all()`);
          }
        }
        lines.push("");
        const vars_zip = listExtractions.map(s => s.name?.toLowerCase().replace(/\s+/g, '_') || 'data').join(', ');
        const vars_list = listExtractions.map(s => (s.name?.toLowerCase().replace(/\s+/g, '_') || 'data') + '_list').join(', ');
        lines.push(`    for ${vars_zip} in zip(${vars_list}):`);
        const dict_items = listExtractions.map(s => `'${s.name}': ${s.name?.toLowerCase().replace(/\s+/g, '_') || 'data'}`).join(', ');
        lines.push(`        print({${dict_items}})`);
        lines.push("");
      }
    }
    lines.push("if __name__ == '__main__':");
    lines.push("    run_scraper()");
    return lines.join('\n');
  }
  
  if (framework === 'scrapling_async') {
    const lines: string[] = [
      "# Generated by Scrapling Visual Builder",
      "import asyncio",
      "from scrapling.fetchers import AsyncStealthyFetcher"
    ];
    if (paginationStep) {
      lines.push("from scrapling import Adaptor");
    }
    lines.push("");
    
    if (paginationStep) {
      const setupSteps = [];
      for (const step of steps) {
        if (step.action === 'pagination') break;
        if (['click', 'fill', 'scroll', 'back', 'forward', 'reload'].includes(step.action)) {
          setupSteps.push(step);
        }
      }
      lines.push("async def perform_actions(page):");
      if (setupSteps.length > 0) {
        for (const step of setupSteps) {
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          if (step.action === 'click') {
            lines.push("    # Click element");
            lines.push(`    await page.click('${sel}')`);
            lines.push("    await page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'fill') {
            lines.push("    # Fill input field");
            lines.push(`    await page.fill('${sel}', '${step.value}')`);
            lines.push("");
          } else if (step.action === 'scroll') {
            lines.push("    # Scroll page");
            lines.push(`    await page.evaluate('window.scrollBy(0, ${step.y})')`);
            lines.push("    await page.wait_for_timeout(1000)");
            lines.push("");
          } else if (step.action === 'back') {
            lines.push("    # Go back in history");
            lines.push("    await page.go_back()");
            lines.push("    await page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'forward') {
            lines.push("    # Go forward in history");
            lines.push("    await page.go_forward()");
            lines.push("    await page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'reload') {
            lines.push("    # Reload page");
            lines.push("    await page.reload()");
            lines.push("    await page.wait_for_load_state('load')");
            lines.push("");
          }
        }
      } else {
        lines.push("    pass");
        lines.push("");
      }

      const pagSel = paginationStep.selector?.replace(/\\/g, '\\\\') || '';
      const maxPages = paginationStep.max_pages || 5;

      lines.push("    # Pagination loop: extract page-by-page");
      lines.push(`    max_pages = ${maxPages}`);
      lines.push("    for page_num in range(1, max_pages + 1):");
      lines.push("        print(f'=== Scraping Page {page_num} ===')");
      lines.push("        response = Adaptor(page.content())");
      lines.push("");

      if (extractions.length > 0) {
        for (const step of extractions) {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          const attr = step.attribute;
          if (attr === 'text') {
            lines.push(`        # Get text from '${sel}'`);
            lines.push(`        ${var_name} = response.css('${sel}::text').get_all()`);
          } else if (attr === 'html') {
            lines.push(`        # Get HTML content`);
            lines.push(`        ${var_name} = response.css('${sel}').get_all()`);
          } else {
            lines.push(`        # Get '${attr}' attribute`);
            lines.push(`        ${var_name} = response.css('${sel}::attr(${attr})').get_all()`);
          }
          lines.push(`        print('${step.name}:', ${var_name})`);
          lines.push("");
        }
      }

      if (listExtractions.length > 0) {
        for (const step of listExtractions) {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          const attr = step.attribute;
          if (attr === 'text') {
            lines.push(`        ${var_name}_list = response.css('${sel}::text').get_all()`);
          } else if (attr === 'html') {
            lines.push(`        ${var_name}_list = response.css('${sel}').get_all()`);
          } else {
            lines.push(`        ${var_name}_list = response.css('${sel}::attr(${attr})').get_all()`);
          }
        }
        lines.push("");
        const vars_zip = listExtractions.map(s => s.name?.toLowerCase().replace(/\s+/g, '_') || 'data').join(', ');
        const vars_list = listExtractions.map(s => (s.name?.toLowerCase().replace(/\s+/g, '_') || 'data') + '_list').join(', ');
        lines.push(`        for ${vars_zip} in zip(${vars_list}):`);
        const dict_items = listExtractions.map(s => `'${s.name}': ${s.name?.toLowerCase().replace(/\s+/g, '_') || 'data'}`).join(', ');
        lines.push(`            print({${dict_items}})`);
        lines.push("");
      }

      lines.push("        if page_num < max_pages:");
      lines.push("            try:");
      lines.push("                # Click next button");
      lines.push(`                await page.click('${pagSel}')`);
      lines.push("                await page.wait_for_load_state('load')");
      lines.push("                await page.wait_for_timeout(2000)");
      lines.push("            except Exception as e:");
      lines.push("                print('No more pages:', e)");
      lines.push("                break");
      lines.push("");

      lines.push("async def run_scraper():");
      lines.push("    # Fetch page stealthily and run automation actions");
      lines.push(`    response = await AsyncStealthyFetcher.fetch('${startUrl}', ${fetchFlags}, page_action=perform_actions)`);
    } else {
      if (interactions.length > 0) {
        lines.push("async def perform_actions(page):");
        for (const step of steps) {
          if (!['click', 'fill', 'scroll', 'back', 'forward', 'reload'].includes(step.action)) continue;
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          if (step.action === 'click') {
            lines.push("    # Click element");
            lines.push(`    await page.click('${sel}')`);
            lines.push("    await page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'fill') {
            lines.push("    # Fill input field");
            lines.push(`    await page.fill('${sel}', '${step.value}')`);
            lines.push("");
          } else if (step.action === 'scroll') {
            lines.push("    # Scroll page");
            lines.push(`    await page.evaluate('window.scrollBy(0, ${step.y})')`);
            lines.push("    await page.wait_for_timeout(1000)");
            lines.push("");
          } else if (step.action === 'back') {
            lines.push("    # Go back in history");
            lines.push("    await page.go_back()");
            lines.push("    await page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'forward') {
            lines.push("    # Go forward in history");
            lines.push("    await page.go_forward()");
            lines.push("    await page.wait_for_load_state('load')");
            lines.push("");
          } else if (step.action === 'reload') {
            lines.push("    # Reload page");
            lines.push("    await page.reload()");
            lines.push("    await page.wait_for_load_state('load')");
            lines.push("");
          }
        }
        lines.push("async def run_scraper():");
        lines.push("    # Fetch page stealthily and run automation actions");
        lines.push(`    response = await AsyncStealthyFetcher.fetch('${startUrl}', ${fetchFlags}, page_action=perform_actions)`);
      } else {
        lines.push("async def run_scraper():");
        lines.push("    # Fetch page stealthily");
        lines.push(`    response = await AsyncStealthyFetcher.fetch('${startUrl}', ${fetchFlags})`);
      }
      lines.push("");
      
      if (extractions.length > 0) {
        lines.push("    # Extract data");
        for (const step of extractions) {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          const attr = step.attribute;
          if (attr === 'text') {
            lines.push(`    ${var_name} = response.css('${sel}::text').get_all()`);
          } else if (attr === 'html') {
            lines.push(`    ${var_name} = response.css('${sel}').get_all()`);
          } else {
            lines.push(`    ${var_name} = response.css('${sel}::attr(${attr})').get_all()`);
          }
          lines.push(`    print('${step.name}:', ${var_name})`);
          lines.push("");
        }
      }
      if (listExtractions.length > 0) {
        lines.push("    # Extract List Data");
        for (const step of listExtractions) {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          const attr = step.attribute;
          if (attr === 'text') {
            lines.push(`    ${var_name}_list = response.css('${sel}::text').get_all()`);
          } else if (attr === 'html') {
            lines.push(`    ${var_name}_list = response.css('${sel}').get_all()`);
          } else {
            lines.push(`    ${var_name}_list = response.css('${sel}::attr(${attr})').get_all()`);
          }
        }
        lines.push("");
        const vars_zip = listExtractions.map(s => s.name?.toLowerCase().replace(/\s+/g, '_') || 'data').join(', ');
        const vars_list = listExtractions.map(s => (s.name?.toLowerCase().replace(/\s+/g, '_') || 'data') + '_list').join(', ');
        lines.push(`    for ${vars_zip} in zip(${vars_list}):`);
        const dict_items = listExtractions.map(s => `'${s.name}': ${s.name?.toLowerCase().replace(/\s+/g, '_') || 'data'}`).join(', ');
        lines.push(`        print({${dict_items}})`);
        lines.push("");
      }
    }
    lines.push("if __name__ == '__main__':");
    lines.push("    asyncio.run(run_scraper())");
    return lines.join('\n');
  }
  
  if (framework === 'playwright_python') {
    const lines: string[] = [
      "# Generated by Scrapling Visual Builder (Raw Playwright Async Exporter)",
      "import asyncio",
      "from playwright.async_api import async_playwright",
      ""
    ];
    lines.push("async def run_scraper():");
    lines.push("    async with async_playwright() as p:");
    lines.push("        browser = await p.chromium.launch(headless=True)");
    lines.push("        context = await browser.new_context(");
    lines.push("            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'");
    lines.push("        )");
    lines.push("        page = await context.new_page()");
    lines.push("");
    lines.push("        # Navigate step");
    lines.push(`        await page.goto('${startUrl}', wait_until='load')`);
    lines.push("");

    if (paginationStep) {
      const setupSteps = [];
      for (const step of steps) {
        if (step.action === 'pagination') break;
        if (['click', 'fill', 'scroll', 'back', 'forward', 'reload'].includes(step.action)) {
          setupSteps.push(step);
        }
      }
      for (const step of setupSteps) {
        const sel = step.selector?.replace(/\\/g, '\\\\') || '';
        if (step.action === 'click') {
          lines.push("        # Click element");
          lines.push(`        await page.click('${sel}')`);
          lines.push("        await page.wait_for_load_state('load')");
          lines.push("");
        } else if (step.action === 'fill') {
          lines.push("        # Fill input field");
          lines.push(`        await page.fill('${sel}', '${step.value}')`);
          lines.push("");
        } else if (step.action === 'scroll') {
          lines.push("        # Scroll page");
          lines.push(`        await page.evaluate('window.scrollBy(0, ${step.y})')`);
          lines.push("        await page.wait_for_timeout(1000)");
          lines.push("");
        } else if (step.action === 'back') {
          lines.push("        # Go back in history");
          lines.push("        await page.go_back()");
          lines.push("        await page.wait_for_load_state('load')");
          lines.push("");
        } else if (step.action === 'forward') {
          lines.push("        # Go forward in history");
          lines.push("        await page.go_forward()");
          lines.push("        await page.wait_for_load_state('load')");
          lines.push("");
        } else if (step.action === 'reload') {
          lines.push("        # Reload active page");
          lines.push("        await page.reload()");
          lines.push("        await page.wait_for_load_state('load')");
          lines.push("");
        }
      }
      
      const pagSel = paginationStep.selector?.replace(/\\/g, '\\\\') || '';
      const maxPages = paginationStep.max_pages || 5;
      
      lines.push("        # Pagination loop: extract page-by-page");
      lines.push(`        max_pages = ${maxPages}`);
      lines.push("        for page_num in range(1, max_pages + 1):");
      lines.push("            print(f'=== Scraping Page {page_num} ===')");
      
      if (extractions.length > 0) {
        for (const step of extractions) {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          lines.push(`            # Extract data: ${step.name}`);
          lines.push(`            elms = await page.query_selector_all('${sel}')`);
          if (step.attribute === 'text') {
            lines.push(`            ${var_name} = [await el.text_content() for el in elms]`);
          } else if (step.attribute === 'html') {
            lines.push(`            ${var_name} = [await el.inner_html() for el in elms]`);
          } else {
            lines.push(`            ${var_name} = [await el.get_attribute('${step.attribute}') for el in elms]`);
          }
          lines.push(`            print('${step.name}:', ${var_name})`);
          lines.push("");
        }
      }
      
      if (listExtractions.length > 0) {
        for (const step of listExtractions) {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          const sel = step.selector?.replace(/\\/g, '\\\\') || '';
          lines.push(`            # Extract list data: ${step.name}`);
          lines.push(`            elms = await page.query_selector_all('${sel}')`);
          if (step.attribute === 'text') {
            lines.push(`            ${var_name}_list = [await el.text_content() for el in elms]`);
          } else if (step.attribute === 'html') {
            lines.push(`            ${var_name}_list = [await el.inner_html() for el in elms]`);
          } else {
            lines.push(`            ${var_name}_list = [await el.get_attribute('${step.attribute}') for el in elms]`);
          }
          lines.push("");
        }
        
        lines.push("            # Print structured list rows");
        const vars_zip = listExtractions.map(s => s.name?.toLowerCase().replace(/\s+/g, '_') || 'data').join(', ');
        const vars_list = listExtractions.map(s => (s.name?.toLowerCase().replace(/\s+/g, '_') || 'data') + '_list').join(', ');
        lines.push(`            for ${vars_zip} in zip(${vars_list}):`);
        const dict_items = listExtractions.map(s => `'${s.name}': ${s.name?.toLowerCase().replace(/\s+/g, '_') || 'data'}`).join(', ');
        lines.push(`                print({${dict_items}})`);
        lines.push("");
      }
      
      lines.push("            if page_num < max_pages:");
      lines.push("                try:");
      lines.push(`                    await page.click('${pagSel}')`);
      lines.push("                    await page.wait_for_load_state('load')");
      lines.push("                    await page.wait_for_timeout(2000)");
      lines.push("                except Exception as e:");
      lines.push("                    print('No more pages:', e)");
      lines.push("                    break");
      lines.push("");
    } else {
      for (const step of steps) {
        if (step.action === 'navigate') continue;
        const sel = step.selector?.replace(/\\/g, '\\\\') || '';
        
        if (step.action === 'click') {
          lines.push("        # Click element");
          lines.push(`        await page.click('${sel}')`);
          lines.push("        await page.wait_for_load_state('load')");
          lines.push("");
        } else if (step.action === 'fill') {
          lines.push("        # Fill input field");
          lines.push(`        await page.fill('${sel}', '${step.value}')`);
          lines.push("");
        } else if (step.action === 'scroll') {
          lines.push("        # Scroll page");
          lines.push(`        await page.evaluate('window.scrollBy(0, ${step.y})')`);
          lines.push("        await page.wait_for_timeout(1000)");
          lines.push("");
        } else if (step.action === 'back') {
          lines.push("        # Go back in history");
          lines.push("        await page.go_back()");
          lines.push("        await page.wait_for_load_state('load')");
          lines.push("");
        } else if (step.action === 'forward') {
          lines.push("        # Go forward in history");
          lines.push("        await page.go_forward()");
          lines.push("        await page.wait_for_load_state('load')");
          lines.push("");
        } else if (step.action === 'reload') {
          lines.push("        # Reload active page");
          lines.push("        await page.reload()");
          lines.push("        await page.wait_for_load_state('load')");
          lines.push("");
        } else if (step.action === 'extract') {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          lines.push(`        # Extract data: ${step.name}`);
          lines.push(`        elms = await page.query_selector_all('${sel}')`);
          if (step.attribute === 'text') {
            lines.push(`        ${var_name} = [await el.text_content() for el in elms]`);
          } else if (step.attribute === 'html') {
            lines.push(`        ${var_name} = [await el.inner_html() for el in elms]`);
          } else {
            lines.push(`        ${var_name} = [await el.get_attribute('${step.attribute}') for el in elms]`);
          }
          lines.push(`        print('${step.name}:', ${var_name})`);
          lines.push("");
        } else if (step.action === 'extract_list') {
          const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
          lines.push(`        # Extract list data: ${step.name}`);
          lines.push(`        elms = await page.query_selector_all('${sel}')`);
          if (step.attribute === 'text') {
            lines.push(`        ${var_name}_list = [await el.text_content() for el in elms]`);
          } else if (step.attribute === 'html') {
            lines.push(`        ${var_name}_list = [await el.inner_html() for el in elms]`);
          } else {
            lines.push(`        ${var_name}_list = [await el.get_attribute('${step.attribute}') for el in elms]`);
          }
          lines.push("");
        }
      }
      
      if (listExtractions.length > 0) {
        lines.push("        # Print structured list rows");
        const vars_zip = listExtractions.map(s => s.name?.toLowerCase().replace(/\s+/g, '_') || 'data').join(', ');
        const vars_list = listExtractions.map(s => (s.name?.toLowerCase().replace(/\s+/g, '_') || 'data') + '_list').join(', ');
        lines.push(`        for ${vars_zip} in zip(${vars_list}):`);
        const dict_items = listExtractions.map(s => `'${s.name}': ${s.name?.toLowerCase().replace(/\s+/g, '_') || 'data'}`).join(', ');
        lines.push(`            print({${dict_items}})`);
        lines.push("");
      }
    }
    
    lines.push("        await browser.close()");
    lines.push("");
    lines.push("if __name__ == '__main__':");
    lines.push("    asyncio.run(run_scraper())");
    return lines.join('\n');
  }
  
  if (framework === 'scrapy_spider') {
    const lines: string[] = [
      "# Generated by Scrapling Visual Builder (Scrapy Spider Exporter)",
      "# Note: Pure Scrapy spiders do not perform dynamic browser clicks/fills",
      "# unless using middlewares like scrapy-playwright.",
      "import scrapy",
      ""
    ];
    lines.push("class ScraplingVisualSpider(scrapy.Spider):");
    lines.push("    name = 'scrapling_spider'");
    lines.push(`    start_urls = ['${startUrl}']`);
    lines.push("");
    lines.push("    def parse(self, response):");
    
    if (interactions.length > 0) {
      lines.push("        # Warning: Page interactions (click/fill) are skipped in Scrapy spider templates");
      for (const step of interactions) {
        if (step.action === 'click') lines.push(`        # - Click on '${step.selector}'`);
        if (step.action === 'fill') lines.push(`        # - Fill '${step.selector}' with value '${step.value}'`);
        if (step.action === 'back') lines.push("        # - Go back in browser history");
        if (step.action === 'forward') lines.push("        # - Go forward in browser history");
        if (step.action === 'reload') lines.push("        # - Reload page");
      }
      lines.push("");
    }
    
    lines.push("        # Extract data");
    if (extractions.length > 0) {
      for (const step of extractions) {
        const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
        const sel = step.selector || '';
        const attr = step.attribute;
        if (attr === 'text') {
          lines.push(`        ${var_name} = response.css('${sel}::text').getall()`);
        } else if (attr === 'html') {
          lines.push(`        ${var_name} = response.css('${sel}').getall()`);
        } else {
          lines.push(`        ${var_name} = response.css('${sel}::attr(${attr})').getall()`);
        }
      }
    }
    
    if (listExtractions.length > 0) {
      for (const step of listExtractions) {
        const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
        const sel = step.selector || '';
        const attr = step.attribute;
        if (attr === 'text') {
          lines.push(`        ${var_name}_list = response.css('${sel}::text').getall()`);
        } else if (attr === 'html') {
          lines.push(`        ${var_name}_list = response.css('${sel}').getall()`);
        } else {
          lines.push(`        ${var_name}_list = response.css('${sel}::attr(${attr})').getall()`);
        }
      }
    }
    
    if (listExtractions.length > 0) {
      lines.push("");
      const vars_zip = listExtractions.map(s => s.name?.toLowerCase().replace(/\s+/g, '_') || 'data').join(', ');
      const vars_list = listExtractions.map(s => (s.name?.toLowerCase().replace(/\s+/g, '_') || 'data') + '_list').join(', ');
      lines.push(`        for ${vars_zip} in zip(${vars_list}):`);
      lines.push(`            yield {`);
      listExtractions.forEach(s => {
        const key = s.name;
        const val = s.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
        lines.push(`                '${key}': ${val},`);
      });
      lines.push(`            }`);
    } else if (extractions.length > 0) {
      lines.push("");
      lines.push("        # Note: Single extractions are yielded as dictionary items");
      lines.push("        yield {");
      extractions.forEach(s => {
        const key = s.name;
        const val = s.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
        lines.push(`            '${key}': ${val},`);
      });
      lines.push("        }");
    } else {
      lines.push("        pass");
    }
    
    if (paginationStep) {
      const pagSel = paginationStep.selector || '';
      lines.push("");
      lines.push("        # Scrapy pagination link following");
      lines.push(`        next_page = response.css('${pagSel}::attr(href)').get()`);
      lines.push("        if next_page is not None:");
      lines.push("            yield response.follow(next_page, callback=self.parse)");
    }
    
    return lines.join('\n');
  }
  
  return "# Unsupported framework format.";
};

const highlightPython = (code: string) => {
  let html = code
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  const comments: string[] = [];
  html = html.replace(/(#.*)/g, (match) => {
    comments.push(match);
    return `___COMMENT_PLACEHOLDER_${comments.length - 1}___`;
  });

  const strings: string[] = [];
  html = html.replace(/(["'])(?:(?=(\\?))\2.)*?\1/g, (match) => {
    strings.push(match);
    return `___STRING_PLACEHOLDER_${strings.length - 1}___`;
  });

  const keywords = /\b(def|class|import|from|async|await|return|if|else|elif|for|in|try|except|print|pass|with|as|zip|yield|None|True|False|self)\b/g;
  html = html.replace(keywords, '<span style="color: #ff79c6; font-weight: 600;">$1</span>');

  const functions = /\b(StealthyFetcher|AsyncStealthyFetcher|fetch|css|get_all|get|zip|print|run_scraper|perform_actions|len|range|evaluate|click|fill|wait_for_load_state|wait_for_timeout|go_back|go_forward|reload)\b/g;
  html = html.replace(functions, '<span style="color: #8be9fd;">$1</span>');

  html = html.replace(/\.([a-zA-Z_][a-zA-Z0-9_]*)/g, '.<span style="color: #50fa7b;">$1</span>');

  html = html.replace(/\b(\d+)\b/g, '<span style="color: #bd93f9;">$1</span>');

  strings.forEach((str, index) => {
    html = html.replace(`___STRING_PLACEHOLDER_${index}___`, `<span style="color: #f1fa8c;">${str}</span>`);
  });

  comments.forEach((comment, index) => {
    html = html.replace(`___COMMENT_PLACEHOLDER_${index}___`, `<span style="color: #6272a4; font-style: italic;">${comment}</span>`);
  });

  return html;
};

export const CodeRunner: React.FC<CodeRunnerProps> = ({ 
  code, 
  sessionId, 
  onStateUpdate, 
  scrapedData = [],
  history = [],
  apiKey = ''
}) => {
  const [copied, setCopied] = useState(false);
  const [isRunning, setIsRunning] = useState(false);
  const [consoleOutput, setConsoleOutput] = useState<string>('Console ready. Click "Run Recipe" to execute the Python script.');
  const [exitCode, setExitCode] = useState<number | null>(null);
  
  const [editableCode, setEditableCode] = useState<string>('');
  const [consoleTab, setConsoleTab] = useState<'console' | 'data'>('console');
  const [selectedFramework, setSelectedFramework] = useState<'scrapling_sync' | 'scrapling_async' | 'playwright_python' | 'scrapy_spider'>('scrapling_sync');
  const [healableError, setHealableError] = useState<{ selector: string; actionType: string } | null>(null);
  const [isHealing, setIsHealing] = useState(false);

  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const preRef = useRef<HTMLPreElement>(null);

  const handleScroll = () => {
    if (textareaRef.current && preRef.current) {
      preRef.current.scrollTop = textareaRef.current.scrollTop;
      preRef.current.scrollLeft = textareaRef.current.scrollLeft;
    }
  };

  useEffect(() => {
    if (history && history.length > 0) {
      const compiled = compileToFramework(history, selectedFramework);
      setEditableCode(compiled);
    } else {
      setEditableCode(code);
    }
  }, [code, history, selectedFramework]);

  useEffect(() => {
    handleScroll();
  }, [editableCode]);

  useEffect(() => {
    if (scrapedData.length > 0) {
      setConsoleTab('data');
    }
  }, [scrapedData.length]);

  const handleCopy = () => {
    navigator.clipboard.writeText(editableCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const extractSelectorFromError = (errorText: string): { selector: string; actionType: string } | null => {
    const patterns = [
      /(?:click|fill)\('([^']+)'\)/,
      /matching selector ['"]([^'"]+)['"]/,
      /querySelectorAll\(['"]([^'"]+)['"]\)/,
      /waiting for selector ['"]([^'"]+)['"]/,
      /Cannot find ['"]([^'"]+)['"]/,
    ];
    const actionPatterns = [
      { re: /page\.click\(/, type: 'click' },
      { re: /page\.fill\(/, type: 'fill' },
      { re: /page\.query_selector_all\(/, type: 'extract' },
      { re: /css\(\'[^']+::text/, type: 'extract' },
    ];
    for (const p of patterns) {
      const m = errorText.match(p);
      if (m) {
        let actionType = 'click';
        for (const ap of actionPatterns) {
          if (errorText.match(ap.re)) { actionType = ap.type; break; }
        }
        return { selector: m[1], actionType };
      }
    }
    return null;
  };

  const handleHealSelector = async (brokenSelector: string, actionType: string) => {
    if (!sessionId || !apiKey) {
      alert('Please set your DeepSeek API Key in the AI Settings panel first.');
      return;
    }
    setIsHealing(true);
    try {
      const response = await fetch('/api/ai/heal-selector', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          session_id: sessionId,
          broken_selector: brokenSelector,
          action_type: actionType,
          api_key: apiKey,
        }),
      });
      if (!response.ok) {
        const err = await response.json();
        throw new Error(err.detail || 'Healing failed');
      }
      const data = await response.json();
      if (data.healed_selector) {
        const updatedCode = editableCode.replaceAll(brokenSelector, data.healed_selector);
        setEditableCode(updatedCode);
        setConsoleOutput(
          prev => prev + `\n\n🤖 AI Healed Selector!\n  Original: "${brokenSelector}"\n  Healed:   "${data.healed_selector}"\n\nClick "Run Recipe" again to retry.\n`
        );
        setHealableError(null);
      } else {
        setConsoleOutput(prev => prev + `\n\n❌ AI could not determine a fix for "${brokenSelector}".\n`);
      }
    } catch (e) {
      setConsoleOutput(prev => prev + `\n\n❌ AI Healing failed: ${e instanceof Error ? e.message : 'Unknown error'}\n`);
    } finally {
      setIsHealing(false);
    }
  };

  const handleRun = async () => {
    if (!editableCode || isRunning) return;
    setIsRunning(true);
    setConsoleOutput('🚀 Executing Python Scrapling script on the active page...\n');
    setExitCode(null);
    setHealableError(null);
    
    try {
      const response = await fetch('/api/run-code', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ session_id: sessionId, code: editableCode })
      });
      
      if (!response.ok) {
        throw new Error('Server returned error executing code');
      }
      
      const data = await response.json();
      
      if (data.state) {
        onStateUpdate(data.state);
      }
      
      let out = '';
      if (data.stdout) {
        out += data.stdout;
      }
      if (data.stderr) {
        out += (out ? '\n' : '') + '⚠️ ERROR/WARNING LOGS:\n' + data.stderr;
      }
      if (!data.stdout && !data.stderr) {
        out = 'Script executed but returned no output (stdout/stderr empty).';
      }
      
      setConsoleOutput(out);
      setExitCode(data.exit_code);
      
      // Check for healable selector errors
      const errorText = (data.stderr || '') + (data.exit_code !== 0 ? '' : '');
      const parsed = extractSelectorFromError(errorText);
      if (parsed && apiKey) {
        setHealableError(parsed);
      }
    } catch (e) {
      const errorMsg = e instanceof Error ? e.message : 'Unknown execution error';
      setConsoleOutput(`❌ Execution failed:\n${errorMsg}`);
      setExitCode(-1);
      const parsed = extractSelectorFromError(errorMsg);
      if (parsed && apiKey) {
        setHealableError(parsed);
      }
    } finally {
      setIsRunning(false);
    }
  };

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      backgroundColor: 'var(--bg-panel)',
      borderTop: '1px solid var(--border-light)',
      overflow: 'hidden'
    }}>
      {/* Code Runner Header */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '8px 16px',
        backgroundColor: 'rgba(0,0,0,0.2)',
        borderBottom: '1px solid var(--border-light)',
        height: '44px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Terminal size={14} color="var(--accent-secondary)" />
          <span style={{ fontSize: '13px', fontWeight: 600 }}>Exporter:</span>
          <select
            value={selectedFramework}
            onChange={(e) => setSelectedFramework(e.target.value as any)}
            style={{
              background: 'var(--bg-main)',
              border: '1px solid var(--border-light)',
              borderRadius: 'var(--radius-sm)',
              padding: '2px 8px',
              color: 'var(--text-primary)',
              fontSize: '12px',
              outline: 'none',
              cursor: 'pointer'
            }}
          >
            <option value="scrapling_sync">Scrapling (Sync)</option>
            <option value="scrapling_async">Scrapling (Async)</option>
            <option value="playwright_python">Playwright (Python)</option>
            <option value="scrapy_spider">Scrapy Spider</option>
          </select>
        </div>

        <div style={{ display: 'flex', gap: '8px' }}>
          <button
            className="btn btn-secondary"
            onClick={handleCopy}
            style={{ height: '28px', padding: '0 10px', fontSize: '11px', gap: '4px' }}
            disabled={!editableCode}
          >
            {copied ? (
              <>
                <Check size={11} color="var(--accent-secondary)" />
                Copied
              </>
            ) : (
              <>
                <Copy size={11} />
                Copy
              </>
            )}
          </button>
          
          <button
            className="btn btn-primary"
            onClick={handleRun}
            style={{ 
              height: '28px', 
              padding: '0 12px', 
              fontSize: '11px', 
              gap: '4px',
              background: 'linear-gradient(135deg, var(--accent-secondary), #0891b2)',
              boxShadow: '0 2px 6px rgba(6, 182, 212, 0.2)'
            }}
            disabled={!editableCode || isRunning}
          >
            {isRunning ? (
              <>
                <Loader size={12} className="loader" />
                Running...
              </>
            ) : (
              <>
                <Play size={11} fill="white" />
                Run Recipe
              </>
            )}
          </button>
        </div>
      </div>

      {/* Grid Layout Split: Textarea Editor on Left, Terminal on Right */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', flex: 1, overflow: 'hidden' }}>
        {/* Left Side: Textarea Editor with Syntax Highlighting */}
        <div style={{
          display: 'flex',
          height: '100%',
          background: '#060910',
          position: 'relative',
          overflow: 'hidden'
        }}>
          <textarea
            ref={textareaRef}
            value={editableCode}
            onChange={(e) => { setEditableCode(e.target.value); setHealableError(null); }}
            onScroll={handleScroll}
            spellCheck={false}
            style={{
              position: 'absolute',
              top: 0,
              left: 0,
              width: '100%',
              height: '100%',
              background: 'transparent',
              color: 'transparent',
              caretColor: '#f8f8f2',
              fontFamily: 'var(--font-mono)',
              fontSize: '12.5px',
              lineHeight: '1.5',
              padding: '16px 16px 60px 16px',
              border: 'none',
              outline: 'none',
              resize: 'none',
              zIndex: 2,
              overflowY: 'auto',
              whiteSpace: 'pre',
              wordWrap: 'normal'
            }}
            placeholder="Write or edit Python code here..."
          />
          <pre
            ref={preRef}
            style={{
              position: 'absolute',
              top: 0,
              left: 0,
              width: '100%',
              height: '100%',
              fontFamily: 'var(--font-mono)',
              fontSize: '12.5px',
              lineHeight: '1.5',
              padding: '16px 16px 60px 16px',
              margin: 0,
              border: 'none',
              whiteSpace: 'pre',
              wordWrap: 'normal',
              overflow: 'hidden',
              zIndex: 1,
              background: 'transparent',
              pointerEvents: 'none',
              color: '#e2e8f0',
              textAlign: 'left'
            }}
            dangerouslySetInnerHTML={{ __html: highlightPython(editableCode) }}
          />
        </div>

        {/* Right Side: Terminal / Scraped Data Tabs */}
        <div style={{
          display: 'flex',
          flexDirection: 'column',
          background: '#020408',
          overflow: 'hidden'
        }}>
          {/* Console/Scraped Data Subheader */}
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            background: 'rgba(255,255,255,0.01)',
            borderBottom: '1px solid var(--border-light)',
            height: '28px',
            padding: '0 8px'
          }}>
            <div style={{ display: 'flex', gap: '8px' }}>
              <button
                onClick={() => setConsoleTab('console')}
                style={{
                  background: 'none',
                  border: 'none',
                  color: consoleTab === 'console' ? 'var(--accent-secondary)' : 'var(--text-muted)',
                  fontSize: '10px',
                  fontWeight: 600,
                  textTransform: 'uppercase',
                  letterSpacing: '0.5px',
                  cursor: 'pointer',
                  padding: '4px 8px',
                  borderBottom: consoleTab === 'console' ? '2px solid var(--accent-secondary)' : 'none'
                }}
              >
                Execution Console
              </button>
              <button
                onClick={() => setConsoleTab('data')}
                style={{
                  background: 'none',
                  border: 'none',
                  color: consoleTab === 'data' ? 'var(--accent-secondary)' : 'var(--text-muted)',
                  fontSize: '10px',
                  fontWeight: 600,
                  textTransform: 'uppercase',
                  letterSpacing: '0.5px',
                  cursor: 'pointer',
                  padding: '4px 8px',
                  borderBottom: consoleTab === 'data' ? '2px solid var(--accent-secondary)' : 'none'
                }}
              >
                Scraped Data ({scrapedData.length})
              </button>
            </div>
            {consoleTab === 'console' && exitCode !== null && (
              <span style={{ 
                fontSize: '10px', 
                color: exitCode === 0 ? '#10b981' : '#ef4444',
                fontWeight: 600 
              }}>
                Process exited with code {exitCode}
              </span>
            )}
            {consoleTab === 'console' && healableError && (
              <button
                onClick={() => handleHealSelector(healableError.selector, healableError.actionType)}
                disabled={isHealing}
                style={{
                  background: 'rgba(236, 72, 153, 0.1)',
                  border: '1px solid rgba(236, 72, 153, 0.3)',
                  borderRadius: 'var(--radius-sm)',
                  color: 'var(--accent-secondary)',
                  fontSize: '10px',
                  fontWeight: 600,
                  cursor: 'pointer',
                  padding: '2px 8px',
                  height: '20px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px',
                }}
                title="Use DeepSeek AI to fix the broken selector"
              >
                {isHealing ? '⏳ Healing...' : '🤖 Heal Selector'}
              </button>
            )}
          </div>
          
          {consoleTab === 'console' ? (
            /* Console Text Area */
            <div style={{
              flex: 1,
              padding: '12px 12px 60px 12px',
              overflowY: 'auto',
              fontFamily: 'var(--font-mono)',
              fontSize: '11px',
              color: '#10b981',
              lineHeight: '1.6',
              whiteSpace: 'pre-wrap',
              textAlign: 'left'
            }}>
              {consoleOutput}
            </div>
          ) : (
            /* Scraped Data Preview Grid */
            <div style={{
              flex: 1,
              padding: '12px 12px 60px 12px',
              overflowY: 'auto',
              display: 'flex',
              flexDirection: 'column'
            }}>
              {scrapedData.length === 0 ? (
                <div style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'center',
                  height: '100%',
                  color: 'var(--text-muted)',
                  fontSize: '12px',
                  textAlign: 'center',
                  padding: '24px'
                }}>
                  <p style={{ marginBottom: '8px', color: 'var(--text-secondary)' }}>No list data scraped yet.</p>
                  <p style={{ fontSize: '11px' }}>Use "Extract List Column" in the canvas context menu to extract sibling components into structured tables.</p>
                </div>
              ) : (
                <table style={{
                  width: '100%',
                  borderCollapse: 'collapse',
                  fontSize: '11.5px',
                  color: 'var(--text-primary)',
                  textAlign: 'left'
                }}>
                  <thead>
                    <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.1)' }}>
                      {Object.keys(scrapedData[0]).map((key) => (
                        <th key={key} style={{ padding: '8px', color: 'var(--accent-secondary)', fontWeight: 600 }}>
                          {key}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {scrapedData.map((row, idx) => (
                      <tr key={idx} style={{ 
                        borderBottom: '1px solid rgba(255,255,255,0.05)',
                        backgroundColor: idx % 2 === 0 ? 'rgba(255,255,255,0.01)' : 'transparent'
                      }}>
                        {Object.keys(scrapedData[0]).map((key) => (
                          <td key={key} style={{ 
                            padding: '8px', 
                            color: 'var(--text-secondary)',
                            fontFamily: 'var(--font-mono)',
                            wordBreak: 'break-all',
                            maxWidth: '200px'
                          }}>
                            {row[key]}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
