import React, { useState } from 'react';
import { Compass, MousePointerClick, Type, ArrowDown, Sparkles, Copy, Trash2, ChevronUp, ChevronDown, GripVertical, ArrowLeft, ArrowRight, RotateCw } from 'lucide-react';

interface WorkflowStep {
  action: 'navigate' | 'click' | 'fill' | 'scroll' | 'extract' | 'extract_list' | 'back' | 'forward' | 'reload';
  url?: string;
  selector?: string;
  value?: string;
  y?: number;
  name?: string;
  attribute?: string;
}

interface WorkflowBuilderProps {
  history: WorkflowStep[];
  onDeleteStep?: (idx: number) => void;
  onReorderSteps?: (draggedIdx: number, targetIdx: number) => void;
}

// Client-side Scrapling Python code compiler
const generateFullPythonScript = (steps: WorkflowStep[]): string => {
  const lines: string[] = [];
  lines.push("# Generated by Scrapling Visual Builder");
  lines.push("from scrapling.fetchers import StealthyFetcher");
  lines.push("");

  let startUrl = "https://example.com";
  for (const step of steps) {
    if (step.action === 'navigate') {
      startUrl = step.url || startUrl;
      break;
    }
  }

  const interactions = steps.filter(s => ['click', 'fill', 'scroll', 'back', 'forward', 'reload'].includes(s.action));
  const extractions = steps.filter(s => s.action === 'extract');
  const listExtractions = steps.filter(s => s.action === 'extract_list');

  if (interactions.length > 0) {
    lines.push("def perform_actions(page):");
    for (const step of steps) {
      if (!['click', 'fill', 'scroll', 'back', 'forward', 'reload'].includes(step.action)) continue;
      const sel = step.selector?.replace(/\\/g, '\\\\') || '';
      if (step.action === 'click') {
        lines.push("    # Click element");
        lines.push(`    page.click('${sel}')`);
        lines.push("    page.wait_for_load_state('load')");
        lines.push("");
      } else if (step.action === 'fill') {
        lines.push("    # Fill input field");
        lines.push(`    page.fill('${sel}', '${step.value}')`);
        lines.push("");
      } else if (step.action === 'scroll') {
        lines.push("    # Scroll page");
        lines.push(`    page.evaluate('window.scrollBy(0, ${step.y})')`);
        lines.push("    page.wait_for_timeout(1000)");
        lines.push("");
      } else if (step.action === 'back') {
        lines.push("    # Go back in history");
        lines.push("    page.go_back()");
        lines.push("    page.wait_for_load_state('load')");
        lines.push("");
      } else if (step.action === 'forward') {
        lines.push("    # Go forward in history");
        lines.push("    page.go_forward()");
        lines.push("    page.wait_for_load_state('load')");
        lines.push("");
      } else if (step.action === 'reload') {
        lines.push("    # Reload page");
        lines.push("    page.reload()");
        lines.push("    page.wait_for_load_state('load')");
        lines.push("");
      }
    }

    lines.push("def run_scraper():");
    lines.push("    # Fetch the page stealthily and run automation actions");
    lines.push(`    response = StealthyFetcher.fetch('${startUrl}', headless=True, page_action=perform_actions)`);
    lines.push("");
  } else {
    lines.push("def run_scraper():");
    lines.push("    # Fetch page stealthily");
    lines.push(`    response = StealthyFetcher.fetch('${startUrl}', headless=True)`);
    lines.push("");
  }

  if (extractions.length > 0) {
    lines.push("    # Extract data");
    for (const step of extractions) {
      const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
      const sel = step.selector?.replace(/\\/g, '\\\\') || '';
      const attr = step.attribute;

      if (attr === 'text') {
        lines.push(`    # Get text from '${sel}'`);
        lines.push(`    ${var_name} = response.css('${sel}::text').get_all()`);
      } else if (attr === 'html') {
        lines.push("    # Get HTML content");
        lines.push(`    ${var_name} = response.css('${sel}').get_all()`);
      } else {
        lines.push(`    # Get '${attr}' attribute`);
        lines.push(`    ${var_name} = response.css('${sel}::attr(${attr})').get_all()`);
      }
      lines.push(`    print('${step.name}:', ${var_name})`);
      lines.push("");
    }
  }

  if (listExtractions.length > 0) {
    lines.push("    # Extract List Data");
    for (const step of listExtractions) {
      const var_name = step.name?.toLowerCase().replace(/\s+/g, '_') || 'data';
      const sel = step.selector?.replace(/\\/g, '\\\\') || '';
      const attr = step.attribute;

      if (attr === 'text') {
        lines.push(`    ${var_name}_list = response.css('${sel}::text').get_all()`);
      } else if (attr === 'html') {
        lines.push(`    ${var_name}_list = response.css('${sel}').get_all()`);
      } else {
        lines.push(`    ${var_name}_list = response.css('${sel}::attr(${attr})').get_all()`);
      }
    }
    
    lines.push("");
    lines.push("    # Print structured table rows");
    const vars_zip = listExtractions.map(s => s.name?.toLowerCase().replace(/\s+/g, '_') || 'data').join(', ');
    const vars_list = listExtractions.map(s => (s.name?.toLowerCase().replace(/\s+/g, '_') || 'data') + '_list').join(', ');
    lines.push(`    for ${vars_zip} in zip(${vars_list}):`);
    
    const dict_items = listExtractions.map(s => `'${s.name}': ${s.name?.toLowerCase().replace(/\s+/g, '_') || 'data'}`).join(', ');
    lines.push(`        print({${dict_items}})`);
    lines.push("");
  }

  lines.push("if __name__ == '__main__':");
  lines.push("    run_scraper()");

  return lines.join('\n');
};

const WorkflowStepCard: React.FC<{
  step: WorkflowStep;
  idx: number;
  history: WorkflowStep[];
  getStepIcon: (action: string) => React.ReactNode;
  getStepDescription: (step: WorkflowStep) => React.ReactNode;
  onDelete?: (idx: number) => void;
  onMoveUp?: (idx: number) => void;
  onMoveDown?: (idx: number) => void;
  onDragStart?: (e: React.DragEvent, idx: number) => void;
  onDragOver?: (e: React.DragEvent, idx: number) => void;
  onDrop?: (e: React.DragEvent, idx: number) => void;
}> = ({ 
  step, 
  idx, 
  history, 
  getStepIcon, 
  getStepDescription,
  onDelete,
  onMoveUp,
  onMoveDown,
  onDragStart,
  onDragOver,
  onDrop
}) => {
  const [copiedCode, setCopiedCode] = useState(false);
  const [copiedSel, setCopiedSel] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  const copyFullCode = (e: React.MouseEvent) => {
    e.stopPropagation();
    const historySlice = history.slice(0, idx + 1);
    const fullCode = generateFullPythonScript(historySlice);
    navigator.clipboard.writeText(fullCode);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 1500);
  };

  const copySelector = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (step.selector) {
      navigator.clipboard.writeText(step.selector);
      setCopiedSel(true);
      setTimeout(() => setCopiedSel(false), 1500);
    }
  };

  return (
    <div 
      draggable={idx > 0} // Don't drag navigation step (usually first step)
      onDragStart={(e) => onDragStart?.(e, idx)}
      onDragOver={(e) => onDragOver?.(e, idx)}
      onDrop={(e) => onDrop?.(e, idx)}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      style={{ 
        display: 'flex', 
        gap: '12px', 
        zIndex: 2,
        cursor: idx > 0 ? 'grab' : 'default',
        opacity: 1,
        transition: 'transform 0.2s ease, box-shadow 0.2s ease'
      }}
    >
      {/* Step indicator circle & Drag handle */}
      <div style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '4px',
        flexShrink: 0,
        marginTop: '4px'
      }}>
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: '22px',
          height: '22px',
          borderRadius: '50%',
          background: 'var(--bg-panel)',
          border: '2px solid var(--border-light)',
        }}>
          <span style={{ fontSize: '10px', fontWeight: 700, color: 'var(--text-muted)' }}>{idx + 1}</span>
        </div>
        
        {idx > 0 && isHovered && (
          <div style={{ color: 'var(--text-muted)', cursor: 'grab' }} title="Drag to reorder">
            <GripVertical size={12} />
          </div>
        )}
      </div>

      {/* Step card */}
      <div style={{
        flex: 1,
        background: 'rgba(255,255,255,0.02)',
        border: '1px solid var(--border-light)',
        borderRadius: 'var(--radius-md)',
        padding: '10px 14px',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
        position: 'relative'
      }}>
        {/* Floating actions (Delete & Move Up/Down) */}
        {isHovered && (
          <div style={{
            position: 'absolute',
            top: '8px',
            right: '8px',
            display: 'flex',
            alignItems: 'center',
            gap: '4px',
            background: 'var(--bg-panel)',
            padding: '2px 4px',
            borderRadius: '4px',
            border: '1px solid var(--border-light)',
            boxShadow: '0 2px 6px rgba(0,0,0,0.2)'
          }}>
            {idx > 1 && (
              <button 
                onClick={(e) => { e.stopPropagation(); onMoveUp?.(idx); }}
                style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', display: 'flex', padding: '2px' }}
                title="Move step up"
              >
                <ChevronUp size={12} />
              </button>
            )}
            {idx > 0 && idx < history.length - 1 && (
              <button 
                onClick={(e) => { e.stopPropagation(); onMoveDown?.(idx); }}
                style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', display: 'flex', padding: '2px' }}
                title="Move step down"
              >
                <ChevronDown size={12} />
              </button>
            )}
            {idx > 0 && (
              <button 
                onClick={(e) => { e.stopPropagation(); onDelete?.(idx); }}
                style={{ background: 'none', border: 'none', color: 'var(--accent-error)', cursor: 'pointer', display: 'flex', padding: '2px' }}
                title="Delete this step"
              >
                <Trash2 size={12} />
              </button>
            )}
          </div>
        )}

        <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px', paddingRight: isHovered ? '50px' : '0' }}>
          <div style={{ marginTop: '2px' }}>
            {getStepIcon(step.action)}
          </div>
          <div style={{ fontSize: '13px', color: 'var(--text-primary)', flex: 1 }}>
            {getStepDescription(step)}
          </div>
        </div>

        {/* Copy Actions Footer */}
        <div style={{ 
          display: 'flex', 
          gap: '8px', 
          borderTop: '1px dashed var(--border-light)', 
          paddingTop: '6px',
          marginTop: '2px'
        }}>
          <button
            onClick={copyFullCode}
            style={{
              background: 'none',
              border: 'none',
              color: copiedCode ? 'var(--accent-secondary)' : 'var(--text-muted)',
              fontSize: '10px',
              fontFamily: 'var(--font-sans)',
              fontWeight: 600,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '4px',
              padding: '2px 4px',
              borderRadius: '2px',
              transition: 'color 0.15s'
            }}
            title="Copy entire Scrapling Python script up to this step"
          >
            <Copy size={10} />
            {copiedCode ? 'Script Copied!' : 'Copy Full Script'}
          </button>

          {step.selector && (
            <button
              onClick={copySelector}
              style={{
                background: 'none',
                border: 'none',
                color: copiedSel ? 'var(--accent-secondary)' : 'var(--text-muted)',
                fontSize: '10px',
                fontFamily: 'var(--font-sans)',
                fontWeight: 600,
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '4px',
                padding: '2px 4px',
                borderRadius: '2px',
                transition: 'color 0.15s'
              }}
              title="Copy element CSS selector to clipboard"
            >
              <Copy size={10} />
              {copiedSel ? 'Selector Copied!' : 'Copy Selector'}
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export const WorkflowBuilder: React.FC<WorkflowBuilderProps> = ({ 
  history,
  onDeleteStep,
  onReorderSteps
}) => {
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);

  const getStepIcon = (action: string) => {
    switch (action) {
      case 'navigate':
        return <Compass size={14} color="var(--accent-secondary)" />;
      case 'click':
        return <MousePointerClick size={14} color="#6366f1" />;
      case 'fill':
        return <Type size={14} color="#a855f7" />;
      case 'scroll':
        return <ArrowDown size={14} color="#ec4899" />;
      case 'extract':
        return <Sparkles size={14} color="var(--accent-warn)" />;
      case 'extract_list':
        return <Sparkles size={14} color="var(--accent-secondary)" />;
      case 'back':
        return <ArrowLeft size={14} color="var(--accent-secondary)" />;
      case 'forward':
        return <ArrowRight size={14} color="var(--accent-secondary)" />;
      case 'reload':
        return <RotateCw size={14} color="var(--accent-secondary)" />;
      default:
        return null;
    }
  };

  const getStepDescription = (step: WorkflowStep) => {
    switch (step.action) {
      case 'navigate':
        return (
          <div>
            <span style={{ fontWeight: 600 }}>Navigate to </span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--accent-secondary)', wordBreak: 'break-all' }}>{step.url}</span>
          </div>
        );
      case 'click':
        return (
          <div>
            <span style={{ fontWeight: 600 }}>Click element </span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: '#818cf8', wordBreak: 'break-all' }}>{step.selector}</span>
          </div>
        );
      case 'fill':
        return (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '2px' }}>
            <div>
              <span style={{ fontWeight: 600 }}>Fill input </span>
              <span style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: '#c084fc', wordBreak: 'break-all' }}>{step.selector}</span>
            </div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
              Value: <span style={{ color: 'var(--text-primary)' }}>"{step.value}"</span>
            </div>
          </div>
        );
      case 'scroll':
        return (
          <div>
            <span style={{ fontWeight: 600 }}>Scroll down </span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: '#f472b6' }}>by {step.y}px</span>
          </div>
        );
      case 'extract':
        return (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '2px' }}>
            <div>
              <span style={{ fontWeight: 600, color: 'var(--accent-warn)' }}>Extract data </span>
              <span>as </span>
              <span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{step.name}</span>
            </div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
              Selector: <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)', wordBreak: 'break-all' }}>{step.selector}</span>
            </div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
              Attribute: <span style={{ color: 'var(--accent-secondary)' }}>{step.attribute}</span>
            </div>
          </div>
        );
      case 'extract_list':
        return (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '2px' }}>
            <div>
              <span style={{ fontWeight: 600, color: 'var(--accent-secondary)' }}>Extract list column </span>
              <span>as </span>
              <span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{step.name}</span>
            </div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
              Selector: <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)', wordBreak: 'break-all' }}>{step.selector}</span>
            </div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
              Attribute: <span style={{ color: 'var(--accent-secondary)' }}>{step.attribute}</span>
            </div>
          </div>
        );
      case 'back':
        return (
          <div>
            <span style={{ fontWeight: 600 }}>Go back </span>
            <span style={{ color: 'var(--text-muted)' }}>in browser history</span>
          </div>
        );
      case 'forward':
        return (
          <div>
            <span style={{ fontWeight: 600 }}>Go forward </span>
            <span style={{ color: 'var(--text-muted)' }}>in browser history</span>
          </div>
        );
      case 'reload':
        return (
          <div>
            <span style={{ fontWeight: 600 }}>Reload </span>
            <span style={{ color: 'var(--text-muted)' }}>active page</span>
          </div>
        );
      default:
        return null;
    }
  };

  // Drag and Drop reordering handlers
  const handleDragStart = (e: React.DragEvent, index: number) => {
    setDraggedIndex(index);
    e.dataTransfer.effectAllowed = 'move';
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const handleDrop = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    if (draggedIndex !== null && draggedIndex !== index && index > 0) {
      onReorderSteps?.(draggedIndex, index);
    }
    setDraggedIndex(null);
  };

  // Move via Button helpers
  const handleMoveUp = (index: number) => {
    if (index > 1) {
      onReorderSteps?.(index, index - 1);
    }
  };

  const handleMoveDown = (index: number) => {
    if (index < history.length - 1) {
      onReorderSteps?.(index, index + 1);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
      {history.length > 0 ? (
        <div style={{ position: 'relative', display: 'flex', flexDirection: 'column', gap: '18px', paddingLeft: '8px' }}>
          {/* Vertical timeline connector */}
          <div style={{
            position: 'absolute',
            left: '17px',
            top: '8px',
            bottom: '8px',
            width: '2px',
            background: 'linear-gradient(to bottom, var(--accent-secondary), var(--accent-primary))',
            zIndex: 1,
            opacity: 0.3
          }} />

          {history.map((step, idx) => (
            <WorkflowStepCard
              key={idx}
              step={step}
              idx={idx}
              history={history}
              getStepIcon={getStepIcon}
              getStepDescription={getStepDescription}
              onDelete={onDeleteStep}
              onMoveUp={handleMoveUp}
              onMoveDown={handleMoveDown}
              onDragStart={handleDragStart}
              onDragOver={handleDragOver}
              onDrop={handleDrop}
            />
          ))}
        </div>
      ) : (
        <div style={{ color: 'var(--text-muted)', fontSize: '13px', padding: '12px', fontStyle: 'italic', textAlign: 'center' }}>
          No workflow actions recorded yet. Navigate to a site and click/inspect elements to build a recipe.
        </div>
      )}
    </div>
  );
};
